#!/usr/bin/env bash
# monitors-detect.sh — detect GPU outputs (DP / HDMI / eDP), propagate to Hyprland + noctalia shell.
#
# Replaces displaylink-hotplug.sh (which targeted EVDI/DVI virtual ports) for systems
# that drive monitors straight off a dedicated GPU. Connector names shift between
# GPUs and ports (DP-0/1, HDMI-A-1/2, …), so instead of hardcoding them we detect the
# actually-connected outputs from `hyprctl monitors` and write the names into:
#   1. ~/.config/hypr/conf/monitors-detected.conf   (Hyprland vars: $EDP $DP $HDMI)
#   2. ~/.config/noctalia/settings.json             (bar/dock/osd/notifications + screenOverrides)
# Then reloads Hyprland and restarts the noctalia shell — but only when the names
# actually changed, so it is cheap to run on every config reload.
#
# Layout assumed (physical):  [DP-?]   [HDMI-?]   with the laptop (eDP) below center.
#   $DP   = left external   (was the EVDI / DVI slot)
#   $HDMI = right external
#   $EDP  = laptop
#
# Usage:
#   monitors-detect.sh             # detect, write conf, update shell, reload
#   monitors-detect.sh --dry-run   # show what would change, apply nothing
#   monitors-detect.sh --status    # show live monitors + current detected conf

set -euo pipefail

# ── Paths ─────────────────────────────────────────────────────────────────────
CONF_DIR="$HOME/.config/hypr/conf"
DETECTED_CONF="$CONF_DIR/monitors-detected.conf"
NOCTALIA_CONF="$HOME/.config/noctalia/settings.json"
SHELL_CMD="/usr/bin/qs -c noctalia-shell"

# ── Logging ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# ── Detection: query hyprctl, echo EDP / DP / HDMI names on separate lines ────
# Pure w.r.t. input (reads hyprctl); returns "" for anything not connected.
detect_monitors() {
    local json
    json="$(hyprctl monitors -j 2>/dev/null)" || { error "hyprctl failed — is Hyprland running?"; return 1; }

    local edp dp hdmi
    edp="$(printf '%s' "$json" | jq -r '[.[] | select(.name | startswith("eDP"))]  | sort_by(.name) | .[0].name // ""' 2>/dev/null)" || edp=""
    # Left external: prefer a real GPU DP output; fall back to legacy DVI (DisplayLink dock).
    dp="$(printf  '%s' "$json" | jq -r '[.[] | select(.name | startswith("DP"))]   | sort_by(.name) | .[0].name // ""' 2>/dev/null)" || dp=""
    if [[ -z "$dp" ]]; then
        dp="$(printf '%s' "$json" | jq -r '[.[] | select(.name | startswith("DVI"))] | sort_by(.name) | .[0].name // ""' 2>/dev/null)" || dp=""
    fi
    hdmi="$(printf '%s' "$json" | jq -r '[.[] | select(.name | startswith("HDMI"))] | sort_by(.name) | .[0].name // ""' 2>/dev/null)" || hdmi=""

    [[ "$edp"  == "null" ]] && edp=""
    [[ "$dp"   == "null" ]] && dp=""
    [[ "$hdmi" == "null" ]] && hdmi=""

    printf '%s\n%s\n%s\n' "$edp" "$dp" "$hdmi"
}

# ── Read a previously-detected var ($EDP/$DP/$HDMI) from the conf file ─────────
read_var() {
    local name="$1"
    [[ -f "$DETECTED_CONF" ]] || return 0
    awk -v n="$name" '
        $0 ~ ("[$]" n "[[:space:]]*=") {
            sub(/^[^=]*=[[:space:]]*/, "")
            gsub(/[[:space:]]/, "")
            print
            exit
        }
    ' "$DETECTED_CONF"
}

# ── Write the detected vars into the sourced conf file ───────────────────────
write_conf() {
    local edp="$1" dp="$2" hdmi="$3" dp_rate="$4"
    cat > "$DETECTED_CONF" <<EOF
# Generated by monitors-detect.sh — do not edit manually.
# Detected connected GPU outputs via \`hyprctl monitors\`.
\$EDP     = ${edp:-eDP-1}
\$DP      = ${dp}
\$DP_RATE = ${dp_rate}
\$HDMI    = ${hdmi}
EOF
}

# ── Update noctalia settings.json: recursive rename of any monitor name ───────
# Maps by connector prefix so it touches bar/dock/osd/notifications/screenOverrides
# in a single pass:  eDP-* → $edp,  HDMI-* → $hdmi,  DVI-*/DP-* → $dp (left slot).
update_noctalia() {
    local edp="$1" dp="$2" hdmi="$3"
    [[ -f "$NOCTALIA_CONF" ]] || { warn "noctalia settings.json not found — skipping shell update."; return 0; }

    local tmp
    tmp="$(mktemp)"
    jq --arg edp "$edp" --arg dp "$dp" --arg hdmi "$hdmi" '
        def mapmon:
            if   . == null   then .
            elif type == "object" then with_entries(.value |= mapmon)
            elif type == "array"  then map(mapmon)
            elif type == "string" then
                     if   (test("^eDP-"))  then $edp
                elif (test("^HDMI-")) then $hdmi
                elif (test("^DVI-"))  then $dp
                elif (test("^DP-"))   then $dp
                else . end
            else . end;
        mapmon
    ' "$NOCTALIA_CONF" > "$tmp" && mv "$tmp" "$NOCTALIA_CONF"
}

# ── Is the noctalia shell config out of sync with detected names? ─────────────
# Stale when detected DP/HDMI is absent from the bar's monitor list (e.g. legacy
# HDMI-A-1 / DVI-I-1 still referenced). Self-heals on every run.
shell_stale() {
    local dp="$1" hdmi="$2"
    [[ -f "$NOCTALIA_CONF" ]] || return 1
    local names
    names="$(jq -r '[.bar.monitors[], .bar.screenOverrides[].name] | unique[]' "$NOCTALIA_CONF" 2>/dev/null)" || return 1
    grep -qx -- "$dp"   <<<"$names" || return 0
    grep -qx -- "$hdmi" <<<"$names" || return 0
    return 1
}

# ── Apply side effects: move workspaces, restart the shell ────────────────────
move_workspaces() {
    local dp="$1" hdmi="$2" ws
    for ws in 4 5 6; do hyprctl dispatch moveworkspacetomonitor "$ws $dp"   >/dev/null 2>&1 || true; done
    for ws in 7 8 9; do hyprctl dispatch moveworkspacetomonitor "$ws $hdmi" >/dev/null 2>&1 || true; done
}

restart_shell() {
    pkill -f "qs -c noctalia-shell" 2>/dev/null || true
    sleep 0.5
    setsid $SHELL_CMD >/dev/null 2>&1 &
}

# ── Status display (--status) ─────────────────────────────────────────────────
show_status() {
    echo -e "${CYAN}Live Hyprland monitors${NC}"
    hyprctl monitors -j 2>/dev/null \
        | jq -r '.[] | "  \(.name)\t\(.description)"' 2>/dev/null \
        || echo "  (Hyprland not running)"
    echo ""
    echo -e "${CYAN}Detected conf ($DETECTED_CONF)${NC}"
    [[ -f "$DETECTED_CONF" ]] && sed 's/^/  /' "$DETECTED_CONF" || echo "  (not generated yet)"
}

# ── Main ──────────────────────────────────────────────────────────────────────
main() {
    local dry_run="false" status_only="false"
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --dry-run) dry_run="true";    shift ;;
            --status)  status_only="true"; shift ;;
            -h|--help) echo "Usage: $(basename "$0") [--dry-run] [--status]"; exit 0 ;;
            *) error "Unknown option: $1"; exit 1 ;;
        esac
    done

    [[ "$status_only" == "true" ]] && { show_status; exit 0; }

    info "Detecting connected GPU outputs..."
    local detected edp dp hdmi
    detected="$(detect_monitors)" || exit 1
    edp="$(sed -n '1p' <<<"$detected")"
    dp="$(sed  -n '2p' <<<"$detected")"
    hdmi="$(sed -n '3p' <<<"$detected")"

    [[ -z "$dp" ]]   && { error "No DP/DVI output detected."; exit 1; }
    [[ -z "$hdmi" ]] && { error "No HDMI output detected."; exit 1; }
    [[ -z "$edp" ]]  && { warn "No eDP output detected (headless/docked?) — leaving \$EDP = eDP-1."; edp="eDP-1"; }

    # Refresh rate of the left external depends on its connector:
    # DP caps at ~75Hz (74.97), legacy DVI/DisplayLink at 60Hz.
    local dp_rate
    if [[ "$dp" == DVI* ]]; then dp_rate="60"; else dp_rate="74.97"; fi

    info "Detected:  eDP=$edp   left=$dp@${dp_rate}Hz   HDMI=$hdmi@75Hz"

    local cur_dp cur_hdmi
    cur_dp="$(read_var DP)"
    cur_hdmi="$(read_var HDMI)"

    local conf_changed="false" shell_needs_update="false"
    [[ "$dp" != "$cur_dp" || "$hdmi" != "$cur_hdmi" ]] && conf_changed="true"
    shell_needs_update="$(shell_stale "$dp" "$hdmi" && echo true || echo false)"

    if [[ "$conf_changed" == "false" && "$shell_needs_update" == "false" ]]; then
        info "Names unchanged ($dp / $hdmi) and shell in sync — reloading Hyprland only."
        [[ "$dry_run" == "false" ]] && { hyprctl reload 2>/dev/null || true; }
        exit 0
    fi

    info "Changes:  conf=$conf_changed  shell=$shell_needs_update   (DP: ${cur_dp:-<none>}→$dp   HDMI: ${cur_hdmi:-<none>}→$hdmi)"

    if [[ "$dry_run" == "true" ]]; then
        warn "Dry-run — no changes made."
        info "[DRY-RUN] write  $DETECTED_CONF  (\$EDP=$edp  \$DP=$dp@\${dp_rate}Hz  \$HDMI=$hdmi)"
        [[ "$shell_needs_update" == "true" ]] && info "[DRY-RUN] update $NOCTALIA_CONF"
        info "[DRY-RUN] hyprctl reload + restart noctalia shell"
        exit 0
    fi

    [[ "$conf_changed" == "true" ]] && { write_conf "$edp" "$dp" "$hdmi" "$dp_rate"; info "Written: $DETECTED_CONF"; }
    [[ "$shell_needs_update" == "true" ]] && { update_noctalia "$edp" "$dp" "$hdmi"; info "Updated: $NOCTALIA_CONF"; }

    hyprctl reload 2>/dev/null || true
    info "Hyprland reloaded."
    sleep 1

    move_workspaces "$dp" "$hdmi"
    restart_shell
    info "Noctalia shell restarted."

    notify-send "Monitor Detect" "eDP=$edp  left=$dp@${dp_rate}Hz  HDMI=$hdmi" 2>/dev/null || true
    info "Done."
}

main "$@"
