fork = false
frame = "full"
idle = true
maximized = false
neovim-bin = "/usr/bin/nvim" # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = false 
tabs = true
theme = "catpuccine"
title-hidden = true
vsync = false 
wsl = false

[font]
normal= ["FiraCode Nerd Font"]

# normal= ["MesloLGS Nerd Font"]
size =10.0
hinting = "full"
edging = "antialias"
