#!/bin/sh
# user preferred settings
#
export XDG_CURRENT_DESKTOP=Hyprland
# export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=Hyprland

# export GDK_BACKEND=wayland,x11
# export QT_QPA_PLATFORM="wayland;xcb"
# export CLUTTER_BACKEND=wayland
# export SDL_VIDEODRIVER=wayland
#
# export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
# export QT_AUTO_SCREEN_SCALE_FACTOR=1
# export QT_QPA_PLATFORMTHEME=qt5ct
#
#export GTK_THEME=Catppuccin-blue:dark
# export GDK_BACKEND=wayland,x11
#
#cursor size
export XCURSOR_SIZE=24

# text editor
# export MICRO_TRUECOLOR=1
export EDITOR=/usr/bin/nvim

#browser
export BROWSER=/usr/bin/brave-bin

#terminal
export TERM=ghostty
#mail
export MAIL=thunderbird

# check /usr/local/bin/hyprstart
