exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
# exec-once = apply-gsettings                           # NOT INSTALLED — Applies GNOME desktop settings
exec-once = dbus-daemon --session --address=unix:path=/run/user/1000/bus --fork
exec-once = dbus-update-activation-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=hyprland
exec-once = nm-applet --indicator &
exec-once = blueman-tray
exec-once = ~/.config/hypr/scripts/monitors-detect.sh
# exec = ~/.local/share/qmk-hid-host/qmk-hid-host
exec-once = ~/.local/bin/wpaperd -d
exec = /usr/libexec/hyprpolkitagent
# exec-once = caelestia shell -d  # replaced by noctalia-shell
exec-once = /usr/bin/qs -c noctalia-shell
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
# exec-once = xwaylandvideobridge                   # NOT INSTALLED — X11 video bridge for Wayland screenshare
exec-once = gentoo-pipewire-launcher &
exec = hyprctl setcursor catppuccin-mocha-dark-cursors 25
exec = gsettings set org.gnome.desktop.interface cursor-theme catppuccin-mocha-dark-cursors
exec = gsettings set org.gnome.desktop.interface cursor-size 25
exec-once = exec xrdb -load ~/.Xresources
