plugin = /usr/lib64/libhy3.so

general {
    gaps_in = 2
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(33ccffee) rgba(8f00ffee) 45deg
    col.inactive_border = rgba(595959aa)
    resize_on_border = true
    layout = hy3
}

cursor {
    enable_hyprcursor = true
    hide_on_key_press = false
    hide_on_touch = false
    no_hardware_cursors = 0
    sync_gsettings_theme = true
}
