exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = apply-gsettings
exec = dbus-daemon --session --address=unix:path=$XDG_RUNTIME_DIR/bus
exec-once = nm-applet --indicator &
exec-once = blueman-tray
exec-once = ~/.config/hypr/scripts/displaylink-hotplug.sh
exec = ~/.local/share/qmk-hid-host/qmk-hid-host
exec-once = ~/.local/bin/wpaperd -d
exec = /usr/libexec/hyprpolkitagent
exec = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=hyprland
# exec-once = caelestia shell -d  # replaced by noctalia-shell
exec-once = /home/aboyarinov/.local/bin/qs -c noctalia-shell
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = xwaylandvideobridge
exec-once = gentoo-pipewire-launcher &
exec = hyprctl setcursor catppuccin-mocha-dark-cursors 25
exec = gsettings set org.gnome.desktop.interface cursor-theme catppuccin-mocha-dark-cursors
exec = gsettings set org.gnome.desktop.interface cursor-size 25
exec-once = exec xrdb -load ~/.Xresources
