device { 
  name = at-translated-set-2-keyboard
    kb_layout = us,ru
    kb_options = grp:win_space_toggle 
    }
device { 
  name = ergohaven-k:03-pro-v1-65mm-keyboard
    kb_layout = us,ru
    kb_options = grp:win_space_toggle 
    }
device { 
  name = ergohaven-k:03-pro-v1-65mm
    kb_layout = us,ru
    kb_options = grp:win_space_toggle 
    }
device { 
  name = ergohaven-k:03-pro-v1-65mm-consumer-control
    kb_layout = us,ru
    kb_options = grp:win_space_toggle 
    }
device { 
  name = charybdis-keyboard
    kb_layout = us,ru
    kb_options = grp:win_space_toggle 
    }
device { 
  name = zmk-project-charybdis-keyboard 
    kb_layout = us,ru
    kb_options = grp:win_space_toggle 
    }
device { 
  name = ergohaven-k:03-pro-v1-65mm-system-control
    kb_layout = us,ru
    kb_options = grp:win_space_toggle 
    }

input {
    numlock_by_default= true
    follow_mouse = 1
    force_no_accel = 0

touchpad {
    natural_scroll = true
    tap-to-click = true
    disable_while_typing = true
    clickfinger_behavior = true
    drag_lock = true
}
tablet {
  relative_input = true
  output = $DL
}

    sensitivity = 0
}
device{
  name  = ergohaven-k:03-pro-v1-65mm-mouse
  sensitivity = 0.7
  }
device {
  name = weylus-stylus---bigme
  sensitivity = -1
}
device {
  name = pen-emu
  sensitivity = -1
}
